# Generated by Django 3.2 on 2021-04-18 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=200)),
                ('image2', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'characters',
            },
        ),
        migrations.CreateModel(
            name='Powers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'powers',
            },
        ),
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_foundation', models.DateField()),
                ('image', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'universe',
            },
        ),
        migrations.CreateModel(
            name='powers_character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('character_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superheroes.character')),
                ('powers_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superheroes.powers')),
            ],
            options={
                'db_table': 'powers_character',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='universe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superheroes.universe'),
        ),
    ]
